cocktailcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('drinks/', views.drinks_index, name='drinks_index'),
  path('drinks/<int:drink_id>/', views.drinks_detail, name='drinks_detail'),
  path('drinks/create/', views.DrinkCreate.as_view(), name='drink_create'),
  path('drinks/<int:pk>/update/', views.DrinkUpdate.as_view(), name='drinks_update'),
  path('drinks/<int:pk>/delete/', views.DrinkDelete.as_view(), name='drinks_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse


GARNISHES= (
  ('E', 'Edible'),
  ('F', 'Flower'),
  ('S', 'Sugar')
)


# Create your models here.
class Drink(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  spirit = models.CharField(max_length=100)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('drinks_detail', kwargs={'drink_id': self.id})

class Presentation(models.Model):
  color = models.CharField(max_length=10)
  garnish = models.CharField(
    max_length=10,
    choices=GARNISHES,
    default=GARNISHES[0][0]
  )
  drink = models.ForeignKey(Drink, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_garnish_display()} is {self.color}"

main_app/forms.py
from django.forms import ModelForm
from .models import Presentation

class PresentationForm(ModelForm):
  class Meta:
    model = Presentation
    fields = ['color', 'garnish']

main_app/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Drink
from .forms import PresentationForm

def __init__(self, name, description, spirit):
    self.name = name
    self.description = description
    self.spirit = spirit



# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request,):
  return render(request, 'about.html')

def drinks_index(request):
  drinks = Drink.objects.all()
  return render(request, 'drinks/index.html', { 'drinks': drinks })

def drinks_detail(request, drink_id):
  drink = Drink.objects.get(id=drink_id)
  presentation_form = PresentationForm()
  return render(request, 'drinks/detail.html', { 
    'drink': drink, 'presentation_form': presentation_form
    })

class DrinkCreate(CreateView):
  model = Drink
  fields = '__all__'

class DrinkUpdate(UpdateView):
  model = Drink
  fields = '__all__'

class DrinkDelete(DeleteView):
  model = Drink
  success_url = '/drinks/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Cocktail Collector</h1>
<hr />
<p class="page-content">
  I like long romantic walks down the produce aisle. Also, I am currently job seeking!
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/splash.svg' %}"
  >
  <title>Cocktail Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="/">
        <img 
        src="{% static 'images/header-logo.svg' %}"
        alt="The Cocktail Collector Logo"
      >
      </a>
    </div>
    <nav>
      <ul>
        <li><a href="{% url 'drink_create' %}">Add a Drink</a></li>
        <li><a href="{% url 'drinks_index' %}">All Drinks</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/drinks/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/cats/cat-detail.css' %}"
/>
{% endblock %}

{% block content %}

<section class="drink-container">
  <div class="drink-img">
    {% comment %} <img 
      src="{% static 'images/sk8r-boi-cat.svg' %}" 
      alt="A skater boy cat"
    > {% endcomment %}
  </div>
    <h2 class="card-title">{{ drink.name }}</h2>
    <h3>A {{ drink.description }} {{ drink.spirit }} based cocktail.</h3>
    <div class="cat-actions">
      <a href="{% url 'drinks_update' drink.id %}" class="btn warn">Edit</a>
      <a href="{% url 'drinks_delete' drink.id %}" class="btn danger">Delete</a>
</section>
<div class="presentations-toy-container">
  <section class="presentations">
    <div class="subsection-title">
      <h2>Presentations</h2>
      {% comment %} <img 
        src="{% static 'images/cat-cone.svg' %}" 
        alt="An ice cream cone cat"
      />
      <img 
        src="{% static 'images/cat-onigiri.svg' %}"
        alt="A cat as onigiri"
      />
      <img 
        src="{% static 'images/kitty-kabob.svg' %}" 
        alt="A kabob of kittens"
      /> {% endcomment %}
    </div>
    <h3>Add a Presentation</h3>
    <form
      method="post" 
      class="subsection-content"
    >
      {% csrf_token %}
      {{ presentation_form.as_p }}
      <button type="submit" class="btn submit">Add Presentation</button>
    </form>
    <h3>Other Presentations</h3>
    <table>
      <thead>
        <tr><th>Color</th><th>Garnish</th></tr>
      </thead>
      <tbody>
        {% for presentation in cat.presentation_set.all %}
          <tr>
            <td>{{presentation.color}}</td>
            <td>{{presentation.get_garnish_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</div>

{% endblock %}

main_app/templates/drinks/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  {% comment %} href="{% static 'css/cats/cat-index.css' %}" {% endcomment %}
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Drink List</h1>
  <img src="{% static 'images/cool-cat.svg' %}" alt="A cool cat" />
  <img src="{% static 'images/happy-cat.svg' %}" alt="A happy cat" />
  <img src="{% static 'images/teacup-cat.svg' %}" alt="A cat in a teacup" />
  <img src="{% static 'images/cat-in-box.svg' %}" alt="A cat in a box" />
</section>

<section class="card-container">
  {% for drink in drinks %}
    <div class="card">
      <a href="{% url 'drinks_detail' drink.id %}">
        <div class="card-content">
          <div class="card-img-container">
            {% comment %} {% comment %} <img 
              src="{% static 'images/sk8r-boi-cat.svg' %}" 
              alt="A skater boy cat"
            > {% endcomment %} 
          </div>
          <h2 class="card-title">{{ drink.name }}</h2>
          {% if drink.name %}
            {% comment %} <p>A {{ cat.age }} year old {{ cat.breed }}</p> {% endcomment %}
            <h3>A {{ drink.description }} {{ drink.spirit }} based cocktail.</h3>
          {% else %}
          <h1>No Cocktails Yet<h1>
          {% endif %}
          <p><small> </small></p>
        </div>
      <a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="drink-container">
    {% comment %} <img src="{% static 'images/splash.svg' %}" alt="The Cat Collector Cat" /> {% endcomment %}
  </div>
  {% comment %} <img 
    src="{% static 'images/logotype.svg' %}" 
    alt="Text reads: Cocktail Collector"
  /> {% endcomment %}
</section>

{% endblock %}

main_app/templates/main_app/drink_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Drink?</h1>
  {% comment %} <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer"/> {% endcomment %}
</div>
<h2>Are you sure you want to delete {{ drink.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'drinks_detail' drink.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/drink_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  {% if drink %}
    <h1>Edit {{ drink.name }}</h1>
  {% else %}
    <h1>Add a Drink</h1>
  {% endif %}
  {% comment %} <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer"/> {% endcomment %}
</div>
{% comment %} 
  Leaving the action empty makes the form post to the same url used to display it
{% endcomment %}
<form action="" method="post" class="form-container">
  {% comment %} 
    Django requires the following for security purposes
  {% endcomment %}
  {% csrf_token %}
  <table>
    {% comment %}
      Render the inputs inside of <tr>s & <td>s
    {% endcomment %}
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}